name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.TARGET_SERVER }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          rsync --archive --compress --delete-after --human-readable \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            --exclude=.git* \
            --exclude=.github/ \
            --exclude=.vscode/ \
            --exclude=node_modules/ \
            --exclude=vendor/ \
